name: drone_stuff
description: "DJI waypoint mission manager for Android"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.6.0+eol
  xml: ^6.6.1
  archive: ^4.0.9
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
